#!/usr/bin/env ruby

incpath = File.dirname(__FILE__)
$:.unshift incpath
require 'rails_env'

gitdir = File.expand_path(File.join(incpath, ".."))

revisions = []
while line = gets
  revisions << line.split(" ")
end

args = [gitdir, revisions]
Task.create(:target_class => "Event", :command => "process", :arguments => args)
